version: '3.2'

services:
  transaction-service:
    image: transaction-service:1.0.0
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    depends_on:
      - db
      - naming-server
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank-transfer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/

  user-service:
    image: user-service:1.0.0
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - db
      - naming-server
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank-transfer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/

  api-gateway:
    image: api-gateway-1.0.0
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/

  naming-server:
    image: naming-server-1.0.0
    build:
      context: ./naming-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank-transfer